### ISSUE TITLE
Log4J input is not working with SocketAppender (Logstash 1.5.2)

### ISSUE THREAD

**Issue by vnyvh** [logstash-plugins/logstash-input-log4j#13] opened 2015-07-15 12:35 UTC
I am using Logstash 1.5.2 and logstash-input-log4j (1.0.0) with Elasticsearch. I am trying to read the events from Log4J SocketAppender. Following is my configuration -
Logstash conf -
log4j {
type => "log4j"
host => "localhost"
port => 4560
add_field => [ "index", "mma-app-log" ]
add_field => [ "parsing", "success" ]
}

Here is my Log4J config -

Whenever I start Logstash I get following warnings -
io/console not supported; tty will not be manipulated
'[DEPRECATED] use require 'concurrent' instead of require 'concurrent_ruby'
log4j:WARN No appenders could be found for logger (org.apache.http.impl.conn.PoolingHttpClientConnectionManager).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Logstash startup completed

And when I start my app server, the SocketAppender throws following error -
ERROR Failed to asynchronously log message: org.apache.logging.log4j.core.async.AsyncLoggerConfigHelper$Log4jEventWrapper@7dbfbfd org.apache.logging.log4j.core.appender.AppenderLoggingException: Error writing to TCP:localhost:4560
at org.apache.logging.log4j.core.net.TcpSocketManager.write(TcpSocketManager.java:134)
at org.apache.logging.log4j.core.appender.OutputStreamManager.write(OutputStreamManager.java:136)
at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:110)
at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:99)
at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:430)
at org.apache.logging.log4j.core.async.AsyncLoggerConfig.asyncCallAppenders(AsyncLoggerConfig.java:121)
at org.apache.logging.log4j.core.async.AsyncLoggerConfigHelper$Log4jEventWrapperHandler.onEvent(AsyncLoggerConfigHelper.java:222)
at org.apache.logging.log4j.core.async.AsyncLoggerConfigHelper$Log4jEventWrapperHandler.onEvent(AsyncLoggerConfigHelper.java:207)
at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Software caused connection abort: socket write error
at java.net.SocketOutputStream.socketWrite0(Native Method)
at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
at org.apache.logging.log4j.core.net.TcpSocketManager.write(TcpSocketManager.java:125)
... 11 more

But if I replace Log4j input with tcp, everything works fine and I do not get any warnings for Logstash.

I am using JDK1.8, Logstash1.5.2, elasticsearch-1.6.0 (all ELK components are downloaded from https://www.elastic.co.

**Comment by mturonne** [comment] 2015-12-07 09:40
Hello,
I am facing the same behavior... 
Tcp input is working whereas the log4j one is not...
Did you find any solution ?
Thank you in advance.

**Comment by vnyvh** [comment] 2015-12-07 16:07
mturinne,
No I did not use the Log4J input due to this reason. And also as per our requirement we introduced the queue to collect all the log events prior to processing.

**Comment by npomaroli** [comment] 2016-11-10 16:01
I have the same problem with Logstash 5, JDK 1.8.
When I start both logstash and my application with the SocketAppender, I can see (with netstat) that the connection is established.
As soon anything is sent to the SocketAppender, I get
`Detected problem with connection: java.net.SocketException: Software caused connection abort: socket write error` and the connection is gone.
Are there any plans to work on this issue, since it is open for over a year now?

**Comment by jordansissel** [comment] 2016-11-10 16:44
@npomaroli is there anything you can do to diagnose further or provide additional details?

**Comment by npomaroli** [comment] 2016-11-11 08:52
@jordansissel I tried now starting logstash with raised log level, and I see the following log entries now:
`[2016-11-11T09:46:14,177][DEBUG][logstash.inputs.log4j    ] Accepted connection {:client=>"10.43.65.16:49861", :server=>"0.0.0.0:4560"}
[2016-11-11T09:46:14,190][DEBUG][logstash.inputs.log4j    ] Closing connection {:client=>"10.43.65.16:49861", :exception=>#<IOError: org.apache.log4j.spi.LoggingEvent; class invalid for deserialization>}`

In my client, I am using log4j 1.2.17 (since the documentation of the log4j plugin specifically states, that it only works with log4j 1.x), but it seems that logstash is using log4j2 now? Could that be the root of the problem?

**Comment by npomaroli** [comment] 2016-11-11 12:42
@jordansissel after updating my test client to log4j2, I get a different "DEBUG" error message in logstash:
`[2016-11-11T13:40:41,510][DEBUG][logstash.inputs.log4j    ] Accepted connection {:client=>"10.43.65.16:50683", :server=>"0.0.0.0:4560"}
[2016-11-11T13:40:41,597][DEBUG][logstash.inputs.log4j    ] Closing connection {:client=>"10.43.65.16:50683", :exception=>#<NoMethodError: undefined method `getRenderedMessage' for #<Java::OrgApacheLoggingLog4jCoreImpl::Log4jLogEvent:0x68d15ef2>>}`

**Comment by zvving** [comment] 2016-11-23 03:24
I had same problem!

```
[2016-11-23T11:14:02,079][DEBUG][logstash.inputs.log4j    ] Accepted connection {:client=>"10.170.182.145:44465", :server=>"0.0.0.0:6001"}
[2016-11-23T11:14:02,274][DEBUG][logstash.instrument.collector] Collector: Sending snapshot to observers {:created_at=>2016-11-23 11:14:02 +0800}
[2016-11-23T11:14:03,106][DEBUG][logstash.inputs.log4j    ] Closing connection {:client=>"10.172.166.158:39609", :exception=>#<IOError: org.apache.log4j.spi.LoggingEvent; class invalid for deserialization>}
```

logstash 5.0.1 & log4j 1.2.17

**Comment by laurencegill** [comment] 2016-11-25 16:02
Same issue here.
logstash server: logstash 5.0,  OpenJDK 1.8
log4j client: log4j 1.2.15, OpenJDK 7, log4j tcp socketappender

```
[2016-11-25T15:22:58,970][DEBUG][logstash.inputs.log4j    ] Accepted connection {:client=>"xx.xx.xx.xx:38464", :server=>"0.0.0.0:4560"}
[2016-11-25T15:23:02,247][DEBUG][logstash.inputs.log4j    ] Closing connection {:client=>"xx.xx.xx.xx:38464", :exception=>#<IOError: org.apache.log4j.spi.LoggingEvent; class invalid for deserialization>}
```

**Comment by guyboertje** [comment] 2016-11-28 16:40
Based on the most recent set of reports, I think that this input is using Log4J v2 and not v1 (jar as bundled with the plugin ruby gem).

It is saying that `org.apache.log4j.spi.LoggingEvent` is not the same as `org.apache.logging.log4j.core.impl.Log4jLogEvent`

But if one sends uses v2 upstream then one gets a method missing error because `getRenderedMessage` is not part of the v2 API on the `Log4jLogEvent` class.

Log4j v2 is being loaded by LS 5.X because of the Java based logging introduced recently.

I am not sure how to setup a config option that can use a better mechanism to find the correct Java class to deserialize the object sent to this input. See JRuby [JRubyObjectInputStream.java line 83](https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/ext/jruby/JRubyObjectInputStream.java#L83).

We can fix it to correctly call the right method on `Log4jLogEvent` but that would only work for upstream sending v2 objects.

**Comment by tsouza** [comment] 2016-11-28 16:50
It also noteworthy to say that the [official docs](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-log4j.html) (even the latest version) states that the plugin only works with v1. So, regardless the solution, we should also update the docs.

**Comment by jordansissel** [comment] 2016-11-28 17:44
Maybe with so many folks reporting problems with this plugin, we should
deprecate it until someone (us, whatever) provides a fix? Otherwise, users
are getting somewhat fooled into using a plugin that has major known
problems?

**Comment by jordansissel** [comment] 2016-11-28 18:57
@tsouza It's not clear to me what this issue is about -- here's what I have in my head for context:

* The original issue was filed against Logstash 1.5, which did not use log4j internally, and we only supported log4j v1
* Later updates seem to be about having log4j v1 talking to Logstash 5.0

It's unclear to me what the problem is. Let's create a new ticket, please.

**Comment by tsouza** [comment] 2016-11-28 18:59
@jordansissel The original issue is this one https://github.com/logstash-plugins/logstash-input-log4j/issues/35

I commented here because you closed that it was a duplicate of this one.

**Comment by jordansissel** [comment] 2016-11-28 19:03
I'm kind of wanting to close this one instead, now. My readon for closing #35 was that @zvving commented on this one and #35 within minutes of eachother saying that they were seeing the same problem. That correlation is enough for me to close the ticket.

If these are separate problems, then we should open a new ticket or revisit #35.

I will close this one because it's ancient and confused by different "me too" reports and I can't make sense of it. I'll re-open #35.

**Closed by jordansissel** 2016-11-28 19:03 UTC

**Comment by jordansissel** [comment] 2016-11-28 19:05
If anyone is experiencing somethign similar to this problem in the future, please create a new ticket.

**Comment by lizhou828** [comment] 2017-05-06 01:57
@npomaroli commented on 11 Nov 2016

I have the same problem with Logstash 5, JDK 1.8.
When I start both logstash and my application with the SocketAppender, I can see (with netstat) that the connection is established.
As soon anything is sent to the SocketAppender, I get
Detected problem with connection: java.net.SocketException: Software caused connection abort: socket write error and the connection is gone.
Are there any plans to work on this issue, since it is open for over a year now?




I got a  same problem . Did anybody know how resovle it ?
![default](https://cloud.githubusercontent.com/assets/5133759/25769025/694fcfec-3242-11e7-94d6-bfe4f7789978.png)

**Comment by untergeek** [comment] 2017-05-06 13:04
@lizhou828 Please see the comment before yours.  Please open a new ticket, this one is closed.
